name: 'ProtoBuffy'
description: 'Build Protobuf by proto version'
inputs:
  origin:
    description: 'protobuf origin'
    required: true
  destination:
    description: 'protobuf destination'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.origin }}
    - ${{ inputs.destination }}