name: 'ProtoBuffy'
description: 'Build Protobuf by proto version'
inputs:
  origin:
    description: 'protobuf origin'
    required: true
  destination:
    description: 'protobuf destination'
    required: true
  access-token:
    description: 'PAT with repository scope (https://github.com/settings/tokens)'
    required: false
  branch-target:
    description: 'pass in branch target to enable build to branches'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.origin }}
    - ${{ inputs.destination }}
    - ${{ inputs.branch-target }}
    - ${{ inputs.access-token }}