name: 'ProtoBuffy'
description: 'Build Protobuf by proto version'
inputs:
  options:
    description: 'test'
    required: false
    default: 'help'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.options }}